os: linux
dist: xenial
language: python

python:
- 3.5
- pypy3.5
- 3.6
- 3.7
- 3.8
- 3.9-dev

matrix:
  include:
    # OSX - 3.6
    - os: osx
      language: generic
      env: MACPYTHON=3.6.8
      before_install: source .travis-osx-install
      script: python setup.py test --addopts "--basetemp=$TMPDIR/pytest"
    # OSX - 3.7
    - os: osx
      language: generic
      env: MACPYTHON=3.7.2
      before_install: source .travis-osx-install
      script: python setup.py test --addopts "--basetemp=$TMPDIR/pytest"


install: pip install -U coveralls
script: python setup.py test
after_success: coveralls